### ISSUE TITLE
Change reorder functions to use select instead of relocate

### ISSUE THREAD

**Issue by fdhidalgo** [fdhidalgo/rais_data_rcode#10]
Can you change the reorder functions to use `select` instead of `relocate`? This way the function is compatible with `dtplyr` and can be called before `as_tibble` is called.  As far as I know, nothing needs to be changed except for the function name. They should work the same. 

https://github.com/fdhidalgo/rais_data_rcode/blob/3be1612954ad5c211ab966fed3ce38771920e2a1/code/masterlist_rais.R#L598

**Comment by emgriggs** [comment]
So, originally I did use select, but it deletes all variables that are not included in the reordering. It appears with the sorting done in the stata code, that the original coder really just wanted to order some variables first. I guess I could get around this by using a select(variables1, variable2, everything()) though. I am also curious if we actually need the reordering given that the variable order tends to change every year in the code and our final collapsed data frame might have an entirely different order.

**Comment by fdhidalgo** [comment]
Ah you are right. In that case, I think we can just remove all the reorder functions. Please delete them from all the relevant functions.
