### ISSUE TITLE
Break up long %>% chain in clean_rais

### ISSUE THREAD

**Issue by fdhidalgo** [fdhidalgo/rais_data_rcode#2]
I generally like pipes for readability, but really long chains are hard to debug. I'd consider breaking up the chain so that we can easily pinpoint where a problem occurs. 

When I tried to debug `clean_rais`, it's essentially impossible using the `debug` function because of the long pipe. Not urgent, but would be good to break up the long `%>%` chain.

**Comment by emgriggs** [comment]
fixed
